package group3.henry.email;

import java.security.SecureRandom;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class EmailTest2 {
   public static void main(String[] args) {
	   /*
	   Requires: Name of recipient
	   			Email add of rec
	   			Autogenerated authentication link
	   			Cliche message
	   			signature
	   */
	  
	   SecureRandom random = new SecureRandom();
	    byte bytes[] = new byte[20];
	    random.nextBytes(bytes);
	    String token = bytes.toString();
	   
	  //recipient
	  String to = "nick2353@gmail.com";        

	  //sender
      String from = "eeit85group3@gmail.com";
      final String username = "eeit85group3@gmail.com";
      final String password = "thisismygroupthreepassword";

      //email host routing
      String host = "smtp.gmail.com";

      Properties props = new Properties();
      props.put("mail.smtp.auth", "true");
      props.put("mail.smtp.starttls.enable", "true");
      props.put("mail.smtp.host", host);
      props.put("mail.smtp.port", "587");

      // Get the Session 
      Session session = Session.getInstance(props, 
    		 new javax.mail.Authenticator() {
	         	protected PasswordAuthentication getPasswordAuthentication() {
	         		return new PasswordAuthentication(username, password);
	         	}
      		 });

      try {         
         Message message = new MimeMessage(session); // Create a default MimeMessage object.

         message.setFrom(new InternetAddress(from)); // Set From: header field of the header.         
         message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to)); // Set To: header field of the header.         
         message.setSubject("Amy Clinic Test Message"); // Set Subject: header field
         message.setText("Hello~~~ this is a sample text!! " + "email sent using JavaMailAPI "); // Set the actual message         
         Transport.send(message); // Send message

         System.out.println("Sent message successfully....");

      } catch (MessagingException e) {
            throw new RuntimeException(e);
      }
   }
}